### ISSUE TITLE
метод compare

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#1]
https://github.com/prista/JD1/blob/57e6b9e7e09a14d4917f78d5dae640dfea7a9e95/src/com/intexsoft/jd1/task04/Exercise4.java#L22-L24

вприцнипе тут написано все нормально.
но в Java принято реализовывать метод compareTo иначе. он возвращает не boolean, а целое число. -1 если 1й объект меньше второго, 0 если равны, и +1 если ....

в твоем случае метод сравнения так не делает. потому его просто надо переименовать во что-то типа isLarger() Или тот же isOverlaps(). наличие слова compare в boolean методе будет смущать тех, кто привыке к стандартам

**Comment by prista** [comment]
resolved
