### ISSUE TITLE
слишком длинное условие

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#10]
https://github.com/prista/JD1/blob/d7b31134ad876a92a78b8cbd0a79d6507fd3bf5d/src/com/intexsoft/jd1/task18/Exercise18.java#L17-L19

мне кажется тут можно было спискок всех пунктуационных символов поместить в отдельную строку. и дальше вместо всех множественных или проверять на строкассимволвами.indexOf(символ). если он там есть, то это искомый символ

**Comment by prista** [comment]
resolved.
solution: regex "[,.!?;:-]+"
