### ISSUE TITLE
неравноценное сравнение

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#11]
https://github.com/prista/JD1/blob/7b0fc40ca6651413c244dbc4e3bc7ccfc48571fb/src/com/itacademy/jd1/task21/Exercise21.java#L7-L19

ничего исправлять не надо. убедись только, что ты понимаешь, что написал. в одном случае ты в буфер добавляешь пробел с буквой s (строку из двух символов). а в другом - плюсуешь к строке интеджер. в итоге тут еще надо потратить время на преобразование этго интеджера. и  на выходе будет 1 символ. вряд ли это сильно меняет результат, но все же не честно сравнил

**Comment by prista** [comment]
Да, косяк. спасибо
