### ISSUE TITLE
непонятный метод

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#14]
https://github.com/prista/JD1/blob/7b0fc40ca6651413c244dbc4e3bc7ccfc48571fb/src/com/itacademy/jd1/task24/Appliances.java#L22-L26

не понимаю что тыт тут хотел написать.
метод printState должен напечать 'state'. а тут если state=false, то ничего не делает. странно. и вряд ли этому есть логичное объяснение

**Comment by prista** [comment]
Забыл вывести значение =) Недоглядел
