### ISSUE TITLE
2 синхронизации подряд

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#18]
https://github.com/prista/JD1/blob/ee1e081e49f5e9177f654c2b945cad60929e1b1f/src/gasstations/solution/StationJob.java#L16

![image](https://user-images.githubusercontent.com/12233334/35510010-5b721a22-0507-11e8-8a32-9495efd364ff.png)

я не понял зачем synchronized стоит на методе run

**Comment by prista** [comment]
миссклик =)
