### ISSUE TITLE
имя метода

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#2]
https://github.com/prista/JD1/blob/57e6b9e7e09a14d4917f78d5dae640dfea7a9e95/src/com/intexsoft/jd1/task05/Exercise5.java#L18

имя метода вообще не говорит о том, что в нем происходит. analizeAmount подошло бы в случае если бы метод был void. т.е. он там что-то проанализировал и ничего не вернул. если же он возвращает что-то, то имя должно примерно говорит что оно вернет (и ява-док уже описывать детали). не надо ничего переименовывать - отлично понимаю что тут трудно придумать адекватное имя и сама задача того не стоит - но хочу обратить внимание на такие вещи

**Comment by prista** [comment]
ok
