### ISSUE TITLE
неправильное использование Caledar

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#4]
https://github.com/prista/JD1/blob/57e6b9e7e09a14d4917f78d5dae640dfea7a9e95/src/com/intexsoft/jd1/task06/Exercise6.java#L18

эта строка лишняя. календарь полученные методом getInstance() уже содержит текущую дату. засовывать в него new Date() нет никакого смысла. метод setTime() в календаре позволяет создавать календари для дат, отличающихся от текущей. если нужна текущая, то не надо трогать этот метод вообще

**Comment by prista** [comment]
resolved
