### ISSUE TITLE
слишком сложное условие

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#6]
https://github.com/prista/JD1/blob/57e6b9e7e09a14d4917f78d5dae640dfea7a9e95/src/com/intexsoft/jd1/task07/Exercise7.java#L25-L30

я не готов сейчас написать "как надо". но видя такую пирамиду из булевских условий сразу возникает мысль, что где-то там как минимум можно вынести метод, который вернет boolean, а условие в if станет намного проще выглядеть после этого

**Comment by dzhivushko** [comment]
не стоит тратить время на исправления, т.к. у меня тоже нету времени на то, чтобы доказать что есть вариант проще.

но 100% такой код можно улучшить

**Comment by prista** [comment]
возможно
