### ISSUE TITLE
Collections usage

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#7]
https://github.com/prista/JD1/blob/57e6b9e7e09a14d4917f78d5dae640dfea7a9e95/src/com/intexsoft/jd1/task09/Exercise9.java#L8

тип переменной лучше делать List, а не ArrayList

И в данном случае использование листа - излишне. если у нас примитив, то подойдет обычный массив примитивов. к нему аналогичный Arrays.sort(array);. разница невелика - просто имей ввиду что такое есть

**Comment by prista** [comment]
непонятно какой длины создвать массив, а в случае с ArrayList можно не париться с такими вопросами

**Comment by prista** [comment]
Исправилен тип ссылки
