### ISSUE TITLE
неправильная трактовка задания

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#8]
https://github.com/prista/JD1/blob/d7b31134ad876a92a78b8cbd0a79d6507fd3bf5d/src/com/intexsoft/jd1/task15/Exercise15.java#L8-L20

ты тут подменил понятия. ты отсортипровал массив. и да, теперь минимум в начале, а максимум в конце. но делать этого не надо было. именно что надо было найти сумму между минимум и максимумом в исходном массиве. и без сортировки алгоритм и результат были бы другими. а так ты просто суммируешь все внутри массива кроме крайних элементов

**Comment by prista** [comment]
Конкретики не было :)
