### ISSUE TITLE
хардкод в размере массива

### ISSUE THREAD

**Issue by dzhivushko** [prista/JD1#9]
https://github.com/prista/JD1/blob/d7b31134ad876a92a78b8cbd0a79d6507fd3bf5d/src/com/intexsoft/jd1/task17/Exercise17.java#L7-L33
ты уже не первый, кому я такое пишу. но решение привязано к размеру массива - 5 на 5
по условию там сказано что он квадратный. но не обязательно 5 на 5. твой алгоритм я не особо понял. наверное он работает как-то. но он очевидно прихардкодан к размеру массива. и если его поменять, то все сломается. 
если я что-то не так понял, то скажи мне завтра

**Comment by prista** [comment]
resolved
